disallowed-methods = [
    { path = "std::option::Option::unwrap", reason = "use proper error handling" },
    { path = "std::result::Result::unwrap", reason = "use proper error handling" },
    { path = "std::option::Option::expect", reason = "use proper error handling" },
    { path = "std::result::Result::expect", reason = "use proper error handling" }
]
